services:
    localstack:
        container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
        image: localstack/localstack-pro:latest # required for Pro
        pull_policy: always
        ports:
            - "127.0.0.1:4566:4566" # LocalStack Gateway
            - "127.0.0.1:4510-4559:4510-4559" # external services port range
            - "127.0.0.1:443:443" # LocalStack HTTPS Gateway (Pro)
        environment:
            # Activate LocalStack Pro: https://docs.localstack.cloud/getting-started/auth-token/
            - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:-} # required for Pro
            - ENABLE_DMS=1
            - ENFORCE_IAM=1
        volumes:
            - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
            - "/var/run/docker.sock:/var/run/docker.sock"
        networks:
            - aws-network
        healthcheck:
            test: curl --fail localhost.localstack.cloud:4566/_localstack/health || exit 1
            interval: 5s
            timeout: 2s
            retries: 5
            start_period: 10s
        restart: always

    mssql_onpremise:
        platform: linux/amd64
        container_name: mssql_onpremise
        image: mcr.microsoft.com/mssql/server:2019-latest
        user: root
        ports:
            - 1433:1433
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Abc1234secure
            - MSSQL_COLLATION=Vietnamese_CI_AS
        networks:
            - aws-network
        volumes:
            - ./mssql/data:/var/opt/mssql/data
            - ./mssql/backups:/var/backups
        restart: always

networks:
    aws-network:
        name: aws-network
