-- TMP_EFZ_FT_HIS
CREATE TABLE "TMP_EFZ_FT_HIS" (
  "ID" bigserial PRIMARY KEY,
  "REF_NO" varchar(200) NOT NULL,
  "TRANSACTION_TYPE" varchar(200),
  "DEBIT_ACCT_NO" varchar(200),
  "DEBIT_CURRENCY" varchar(50),
  "AMOUNT_DEBITED" varchar(200),
  "DEBIT_VALUE_DATE" varchar(50),
  "CREDIT_ACCT_NO" varchar(200),
  "CREDIT_CURRENCY" varchar(50),
  "AMOUNT_CREDITED" varchar(200),
  "CREDIT_VALUE_DATE" varchar(50),
  "DEBIT_COMP_CODE" varchar(200),
  "CREDIT_COMP_CODE" varchar(200),
  "BUSINESS_DATE" varchar(20) NOT NULL,
  "RECORD_STATUS" varchar(300),
  "SERVICE_CHANNEL" varchar(50),
  "BEN_ACCT_NO" varchar(50),
  "ATM_RE_NUM" varchar(500),
  "CO_CODE" varchar(500),
  "VPB_SERVICE" varchar(250),
  "CONTACT_NUM" varchar(250),
  "DEBIT_CUSTOMER" varchar(250),
  "BOND_CODE" varchar(500),
  "PR_CARD_NO" varchar(500),
  "BEN_LEGAL_ID" varchar(500),
  "BEN_ID_CUSTOMER" varchar(500),
  "DEBIT_THEIR_REF" varchar(500),
  "CREDIT_CARD" varchar(200),
  "PROCESSING_DATE" varchar(50),
  "CREDIT_AMOUNT" varchar(50),
  "DEBIT_AMOUNT" varchar(50),
  "CREDIT_THEIR_REF" varchar(50),
  "AT_AUTH_CODE" varchar(50),
  "TOTAL_CHARGE_AMT" varchar(100),
  "ATM_TERM_ID" varchar(100),
  "PROFIT_CENTRE_CUST" varchar(30),
  "TREASURY_RATE" varchar(50),
  "SOURCE_OF_FCY" varchar(35),
  "VALUE_DT_LOCAL" varchar(35),
  "VAT_NAME" varchar(100),
  "R_CI_CODE" varchar(35),
  "PURPOSE" varchar(300),
  "B_ID_ISSUE_PLAC" varchar(35),
  "CARD_NUMBER" varchar(35),
  "TYPE_OF_DOC" varchar(10),
  "VAT_CIF_NO" varchar(100),
  "AUTHORISER" varchar(500),
  "VPB_AUTHORISER" varchar(500),
  "BAL_AFT_TXN" varchar(100),
  "AT_MC_TRANS" varchar(200),
  "TOTAL_TAX_AMOUNT" varchar(35),
  "AUTH_DATE" varchar(10),
  "SENDING_ACCT" varchar(100),
  "DEPT_CODE" varchar(10),
  "VPB_INPUTTER" varchar(200)
);

-- TMP_EFZ_FT_HIS_DETAILS
CREATE TABLE "TMP_EFZ_FT_HIS_DETAILS" (
  "ID" bigserial PRIMARY KEY,
  "REF_NO" varchar(200) NOT NULL,
  "M" int,
  "S" int,
  "DATE_TIME" varchar(300),
  "BUSINESS_DATE" varchar(20),
  "PAYMENT_DETAILS" varchar(500),
  "TXN_DETAIL_VPB" varchar(500),
  "TXN_DETAIL" varchar(500),
  "RECEIVING_NAME" varchar(500),
  "REF_DATA_VALUE" varchar(50),
  "REF_DATA_ITEM" varchar(50),
  "INPUTTER" varchar(200),
  "BEN_CUSTOMER" varchar(300),
  "RECEIVING_ADDR" varchar(300),
  "ORDERING_CUST" varchar(300),
  "SENDING_ADDR" varchar(300),
  "COMMISSION_AMT" varchar(35)
);

-- TMP_EFZ_FT_AFTER_COB
CREATE TABLE "TMP_EFZ_FT_AFTER_COB" (
  "ID" bigserial PRIMARY KEY,
  "REF_NO" varchar(200) NOT NULL,
  "TRANSACTION_TYPE" varchar(200),
  "DEBIT_ACCT_NO" varchar(200),
  "DEBIT_CURRENCY" varchar(50),
  "AMOUNT_DEBITED" varchar(200),
  "DEBIT_VALUE_DATE" varchar(50),
  "CREDIT_ACCT_NO" varchar(200),
  "CREDIT_CURRENCY" varchar(50),
  "AMOUNT_CREDITED" varchar(200),
  "CREDIT_VALUE_DATE" varchar(50),
  "DEBIT_COMP_CODE" varchar(200),
  "CREDIT_COMP_CODE" varchar(200),
  "BUSINESS_DATE" varchar(20) NOT NULL,
  "RECORD_STATUS" varchar(300),
  "SERVICE_CHANNEL" varchar(50),
  "BEN_ACCT_NO" varchar(50),
  "BOND_CODE" varchar(500),
  "VPB_SERVICE" varchar(250),
  "CONTACT_NUM" varchar(250),
  "DEBIT_CUSTOMER" varchar(250),
  "ATM_RE_NUM" varchar(500),
  "CO_CODE" varchar(500),
  "PR_CARD_NO" varchar(500),
  "BEN_LEGAL_ID" varchar(500),
  "BEN_ID_CUSTOMER" varchar(500),
  "DEBIT_THEIR_REF" varchar(500),
  "CREDIT_CARD" varchar(200),
  "SECTOR" varchar(50),
  "PURPOSE" varchar(300),
  "VPB_BEN_COUNTRY" varchar(50),
  "ORDER_COUNTRY" varchar(50),
  "SOURCE_OF_FCY" varchar(50),
  "PTTT" varchar(50),
  "DAO" varchar(50),
  "KBB_RATE" varchar(50),
  "PRODUCT_LINE" varchar(500),
  "LD_CONTRACT_NO" varchar(100),
  "AUTHORISER" varchar(100),
  "VAT_CIF_NO" varchar(100),
  "BC_BANK_SORT_CODE" varchar(100),
  "SENDING_ACCT" varchar(100),
  "CLASSIFY_CODE" varchar(100),
  "DEPT_CODE" varchar(100),
  "BEN_OUR_CHARGES" varchar(100),
  "TERM" varchar(100),
  "TOTAL_CHARGE_AMT" varchar(100),
  "VPB_INPUTTER" varchar(500),
  "VPB_AUTHORISER" varchar(500),
  "BOOKING_SERVICE" varchar(100),
  "CHARGES_ACCT_NO" varchar(100),
  "PROFIT_CENTRE_CUST" varchar(100),
  "PROCESSING_DATE" varchar(100),
  "RECEIVER_BANK" varchar(100),
  "DELIVERY_INREF" varchar(100),
  "ATM_TERM_ID" varchar(100),
  "TREASURY_RATE" varchar(50),
  "VALUE_DT_LOCAL" varchar(35),
  "VAT_NAME" varchar(100),
  "R_CI_CODE" varchar(35),
  "B_ID_ISSUE_PLAC" varchar(35),
  "CARD_NUMBER" varchar(35),
  "AT_AUTH_CODE" varchar(10),
  "AUTH_DATE" varchar(10),
  "CREDIT_CUSTOMER" varchar(35),
  "CREDIT_THEIR_REF" varchar(35),
  "TYPE_OF_DOC" varchar(10),
  "DEBIT_AMOUNT" varchar(50),
  "BAL_AFT_TXN" varchar(100),
  "AT_MC_TRANS" varchar(200),
  "TOTAL_TAX_AMOUNT" varchar(35)
);

-- TMP_EFZ_FT_AFTER_COB_DETAILS
CREATE TABLE "TMP_EFZ_FT_AFTER_COB_DETAILS" (
  "ID" bigserial PRIMARY KEY,
  "REF_NO" varchar(200) NOT NULL,
  "M" int,
  "S" int,
  "DATE_TIME" varchar(300),
  "BUSINESS_DATE" varchar(20),
  "PAYMENT_DETAILS" varchar(500),
  "TXN_DETAIL_VPB" varchar(500),
  "TXN_DETAIL" varchar(500),
  "RECEIVING_NAME" varchar(500),
  "NAME_OF_GOODS" varchar(500),
  "ORDERING_BANK" varchar(100),
  "ACCT_WITH_BANK" varchar(100),
  "REF_DATA_VALUE" varchar(100),
  "INPUTTER" varchar(500),
  "ORDERING_CUST" varchar(300),
  "AZ_LD_NRDATE" varchar(100),
  "BEN_CUSTOMER" varchar(300),
  "SUSPENSE_ID" varchar(100),
  "REF_DATA_ITEM" varchar(100),
  "RECEIVING_ADDR" varchar(300),
  "SENDING_ADDR" varchar(300),
  "COMMISSION_AMT" varchar(35)
);

-- TMP_EFZ_FUNDS_TRANSFER
CREATE TABLE "TMP_EFZ_FUNDS_TRANSFER" (
  "ID" bigserial PRIMARY KEY,
  "REF_NO" varchar(200) NOT NULL,
  "TRANSACTION_TYPE" varchar(200),
  "DEBIT_ACCT_NO" varchar(200),
  "DEBIT_CURRENCY" varchar(50),
  "AMOUNT_DEBITED" varchar(200),
  "DEBIT_VALUE_DATE" varchar(50),
  "CREDIT_ACCT_NO" varchar(200),
  "CREDIT_CURRENCY" varchar(50),
  "AMOUNT_CREDITED" varchar(200),
  "CREDIT_VALUE_DATE" varchar(50),
  "DEBIT_COMP_CODE" varchar(200),
  "CREDIT_COMP_CODE" varchar(200),
  "BUSINESS_DATE" varchar(20) NOT NULL,
  "RECORD_STATUS" varchar(300),
  "SERVICE_CHANNEL" varchar(50),
  "BEN_ACCT_NO" varchar(50),
  "BOND_CODE" varchar(500),
  "VPB_SERVICE" varchar(250),
  "CONTACT_NUM" varchar(250),
  "DEBIT_CUSTOMER" varchar(250),
  "ATM_RE_NUM" varchar(500),
  "CO_CODE" varchar(500),
  "PR_CARD_NO" varchar(500),
  "BEN_LEGAL_ID" varchar(500),
  "BEN_ID_CUSTOMER" varchar(500),
  "DEBIT_THEIR_REF" varchar(500),
  "CREDIT_CARD" varchar(200),
  "PROCESSING_DATE" varchar(50),
  "CREDIT_AMOUNT" varchar(50),
  "DEBIT_AMOUNT" varchar(50),
  "CREDIT_THEIR_REF" varchar(50),
  "AT_AUTH_CODE" varchar(50),
  "TOTAL_CHARGE_AMT" varchar(100),
  "ATM_TERM_ID" varchar(100),
  "PROFIT_CENTRE_CUST" varchar(100),
  "VAT_CIF_NO" varchar(100),
  "AUTHORISER" varchar(200),
  "VPB_AUTHORISER" varchar(50),
  "TREASURY_RATE" varchar(50),
  "TYPE_OF_DOC" varchar(10),
  "SOURCE_OF_FCY" varchar(35),
  "VALUE_DT_LOCAL" varchar(35),
  "VAT_NAME" varchar(100),
  "R_CI_CODE" varchar(35),
  "PURPOSE" varchar(300),
  "B_ID_ISSUE_PLAC" varchar(35),
  "BAL_AFT_TXN" varchar(100),
  "AT_MC_TRANS" varchar(200),
  "TOTAL_TAX_AMOUNT" varchar(35),
  "AUTH_DATE" varchar(10),
  "SENDING_ACCT" varchar(100),
  "DEPT_CODE" varchar(10),
  "VPB_INPUTTER" varchar(200)
);

-- TMP_EFZ_FUNDS_TRANSFER_DETAILS
CREATE TABLE "TMP_EFZ_FUNDS_TRANSFER_DETAILS" (
  "ID" bigserial PRIMARY KEY,
  "REF_NO" varchar(200) NOT NULL,
  "M" int,
  "S" int,
  "DATE_TIME" varchar(300),
  "BUSINESS_DATE" varchar(20),
  "PAYMENT_DETAILS" varchar(500),
  "TXN_DETAIL_VPB" varchar(500),
  "TXN_DETAIL" varchar(500),
  "RECEIVING_NAME" varchar(500),
  "REF_DATA_VALUE" varchar(50),
  "REF_DATA_ITEM" varchar(50),
  "INPUTTER" varchar(200),
  "BEN_CUSTOMER" varchar(300),
  "RECEIVING_ADDR" varchar(300),
  "ORDERING_CUST" varchar(300),
  "SENDING_ADDR" varchar(300),
  "COMMISSION_AMT" varchar(35)
);
